// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use embedded SQLite database in the project root
    // Production deployments will override with their own DATABASE_URL
    url: process.env["DATABASE_URL"] || `file:${path.join(process.cwd(), "ev-database.db")}`,
  },
});
